### ISSUE TITLE
0.3.3版本无法下载

### ISSUE THREAD

**Issue by kuzen** [apades/dmMiniPlayer#1]
chrome扩展商店上点下载会出错，其它插件无问题。

![image](https://github.com/apades/dmMiniPlayer/assets/16202160/854d791a-d2a0-4fbf-869b-c9b78288b8fb)

**Comment by apades** [comment]
你chrome多少版本呢我看看，有可能是我升级了框架版本打包出来的不兼容旧的了

**Comment by kuzen** [comment]
> 你chrome多少版本呢我看看，有可能是我升级了框架版本打包出来的不兼容旧的了

Chrome Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by kuzen** [comment]
从正常电脑中提取出插件，放到 linux 中，用开发者模式加载插件，会报
```
Could not find key specification for 'command[1].suggested_key': Either specify a key for 'linux', or specify a default key.
Could not load manifest.
```

**Comment by apades** [comment]
😂基本不用linux的，给漏了这个快捷键设置了

**Comment by apades** [comment]
0.3.4 已修复非window/mac系统快捷键问题
