### ISSUE TITLE
b站播放AV号视频时，运行dmMiniPlayer无弹幕，BV号正常。

### ISSUE THREAD

**Issue by bakaxiaofang** [apades/dmMiniPlayer#15]
如果启用了Bilibili-Evolved插件中的`网址AV号转换`，运行dmMiniPlayer的话弹幕并不会加载。

AV号无弹幕图片

![AV号无弹幕图片](https://cirno.bakaxiaofang.moe/ImageSharing/1716103119765)

BV号有弹幕图片

![BV号有弹幕图片](https://cirno.bakaxiaofang.moe/ImageSharing/1716103131068)

**Comment by apades** [comment]
啊没想到还有这个av情况😨我后面再兼容吧
