### ISSUE TITLE
2个改善建议：鼠标拖动位置和进度条显示时间帧。

### ISSUE THREAD

**Issue by mlc2743** [apades/dmMiniPlayer#16]
1. 建议鼠标可以拖动画中画里的任意位置实现整个画中画的移动。
2. 建议鼠标放在进度条上时显示鼠标所在位置的时间帧。

**Comment by apades** [comment]
1是不可能的，我没有权限操作已经打开的窗口位置也没有相关功能，2最近放假我可以优化下

**Comment by mlc2743** [comment]
> 1是不可能的，我没有权限操作已经打开的窗口位置也没有相关功能，2最近放假我可以优化下

谢谢回复。
我不太懂这个哈，因为旧的画中画是可以鼠标拖动任意位置来移动的，所以以为这个新的也可以这样弄。

另外还发现这个新的画中画，GlobalSpeed的全局快捷键对它无效，就好像是跟浏览器完全断绝联系了一样，感觉它是比较适合看直播的。

**Comment by apades** [comment]
因为他就是一个独立的窗口的，你在原本窗口上插入的脚本什么的都不会在里面触发，按键这些也是😂我里面就带了长按右键3倍速播放的功能，其实我都经常拿来看视频，还是挺喜欢b站这种长按倍速的功能
