### ISSUE TITLE
B 站分 P 弹幕问题

### ISSUE THREAD

**Issue by ChuChencheng** [apades/dmMiniPlayer#17]
B 站分 P 视频，自动播放到下一 P 时，弹幕还是上一 P  的内容，并且弹幕大小设置会被重置。

**Comment by apades** [comment]
这个要晚点才能解决了，我最近才发现换了新框架后忘记把这个相关的代码启用了，而且这代码框架打包还出了问题没法用😅先暂时刷新下吧，后面再换个框架就好了

**Comment by niu541412** [comment]
另外我发现类似的问题。播放自建的收藏夹或者up主做的合集，弹幕都不显示。

**Comment by apades** [comment]
> 另外我发现类似的问题。播放自建的收藏夹或者up主做的合集，弹幕都不显示。

@niu541412 给一个出问题的url我看看吧，我这边看的合集都没问题

**Comment by niu541412** [comment]
好像还真是，有的合集就没问题。
下面这些个，大佬可以你那测试下。我电脑上都不行。
[合集1](https://www.bilibili.com/list/473965081)
[合集2](https://www.bilibili.com/list/3546661949279155)
[收藏夹1](https://www.bilibili.com/list/ml1057887954)
[收藏夹2](https://www.bilibili.com/list/ml1560069352)

**Comment by apades** [comment]
fbbe9902b5934ba1daff4665cb454343887a9ba3 v0.5.0版本修复了
