### ISSUE TITLE
mac画中画小窗口上没有关闭按钮

### ISSUE THREAD

**Issue by langoyb** [apades/dmMiniPlayer#2]
很不错的插件，至少是我目前能找到的唯一支持带进度条的画中画插件，希望作者继续优化，

**Comment by apades** [comment]
请问你是哪个网站出现了关闭画中画没有还原视频的，我去看看

**Comment by langoyb** [comment]
mac 13.6，youtube下，点击左上角图标可以出现带进度条的画中画，我很需要这个功能。可是目前还没找到怎样将画中画还原至原生模式（直接使用yt的画中画功能，在弹出式PIP中会有返回至标签页提示）。在你的项目内没有这个选项。也不知道是不是我操作不对，或者说有什么快捷键可以实现该功能。另外弹出式小窗貌似不能任意拖动。谢谢你的热心回复！

**Comment by apades** [comment]
我不是很清楚mac是怎么个表现呢，我window是这样的[](https://www.awesomescreenshot.com/video/21601817?key=f6ca0b72e0f8e6267c132c19ae1d20b9)

**Comment by langoyb** [comment]
或者我换个问法，怎样关闭弹出的小窗

**Comment by apades** [comment]
你移动鼠标到小窗右上角没有关闭按钮吗，你截图我看看呢

**Comment by langoyb** [comment]
我这里没有
<img width="2268" alt="截屏2023-10-15 18 28 25" src="https://github.com/apades/dmMiniPlayer/assets/140099544/9f5376d4-2e68-4e44-a4ec-a3bf02d05fc3">

**Comment by apades** [comment]
你移动鼠标进小窗是可以弹出我录像里的那个播放控制器吧🤔我怀疑是mac支持不全，要不你升级下浏览器；或者在设置里把新版画中画关了，用旧版本也是有进度条功能；要不想用旧版本也可以试试快捷键
![image](https://github.com/apades/dmMiniPlayer/assets/36807043/3dae5d15-c9cf-4241-a112-364ffd4562a5)

**Comment by apades** [comment]
毕竟这新画中画API这2 3个月chromium那边就放stable上了，而且这个功能还不是w3c官方草案的是chrome那边强推的🤣

**Comment by langoyb** [comment]
刚刚测试了，在win下是有关闭按钮的，这样看来就是对MAC的支持不好。
非常感谢你的热心解答，也祝该项目越来越好！

**Comment by apades** [comment]
没事，也谢谢你的问题提供

**Comment by langoyb** [comment]
如果有一天支持MAC使用了，我会回来使用的
