### ISSUE TITLE
Twitch 弹幕重复

### ISSUE THREAD

**Issue by Mishasama** [apades/dmMiniPlayer#21]
![image](https://github.com/user-attachments/assets/71a0bf76-0396-455e-9f66-7025d8fdbfd4)
如图
Edge 126.0.2592.87

**Comment by apades** [comment]
edge版本旧的啊，你有chrome不。chrome现在是0.5了，edge还在0.4.5，0.5我才修了一些js注入的问题可能跟这个有关，我这边chrome是正常的。我好讨厌上传edge啊👿edge审核贼慢网页管理页又难用

**Comment by Mishasama** [comment]
但你架不住edge的bug比chrome少啊……而且还有SVR。现在看视频不开SVR大会员都给你整成DVD画质啊……
chrome我实在不想再用了，全是bug经常要重装。
如果你讨厌上传，你可以弄个脚本自动推送啊……

**Comment by apades** [comment]
edge的docPIP好像不支持svr，我那评论区有人提了。这一开始edge对docPIP的支持挺差的提了好多反馈给官方都不回的，从116开始到现在126才把容易崩溃卡顿和红色tab栏给修了，我印象挺差的。我已经传了edge商店了，要不你先下[chrome](https://chromewebstore.google.com/detail/%E5%BC%B9%E5%B9%95%E7%94%BB%E4%B8%AD%E7%94%BB%E6%92%AD%E6%94%BE%E5%99%A8/nahbabjlllhocabmecfjmcblchhpoclj?authuser=0&hl=zh-CN)的吧，反正都支持。还有自动推送这事只能后面再弄，有好多东西要测试，现在不是主要目标

**Comment by Mishasama** [comment]
> 0.5我才修了一些js注入的问题可能跟这个有关

实测chrome的0.5无论在chrome还是edge上依然有双重弹幕问题。

---

> edge的docPIP好像不支持svr

我这边测试鲜艳模式是支持的，截图里的就是开了SVR的效果，不然画面就是占满的。
也就有那么一点兼容性问题……但是PIP本来就低分辨率，搭配低分辨率码流上SVR简直绝配。而且用docPIP的话还能自动强制1：1分辨率显示，锐度比老PIP的默认大小好多了，或者比要手动调节到1：1分辨率方便多了😂

> 提了好多反馈给官方都不回的

微软是这样的，全部都是已读不回，无论是国内团队还是国外团队都这样。但实际上试过好几次反馈后过了几个版本都发现去修了，估计是工作量问题，不太像是态度问题。不然他们完全可以用copilot全自动回复来忽悠我们。

> 从116开始到现在126才把容易崩溃卡顿和红色tab栏给修了，我印象挺差的。

关于这个问题，应该不是edge的事，而是chromium的事……edge在这方面还是有点被动的。
bug修得慢其实chrome也是这样的，你可以参考一下[这个BUG](https://github.com/andywang425/BLTH/issues/499#issuecomment-2228759733)，看看到正式修复它都要花了多少年了……作为第三方我们都很无奈😓

> 我已经传了edge商店了，要不你先下[chrome](https://chromewebstore.google.com/detail/%E5%BC%B9%E5%B9%95%E7%94%BB%E4%B8%AD%E7%94%BB%E6%92%AD%E6%94%BE%E5%99%A8/nahbabjlllhocabmecfjmcblchhpoclj?authuser=0&hl=zh-CN)的吧

至于商店的话，chrome是出了名的野蛮操作，动不动就给你下架，还强制MV3。反观edge就没这些臭毛病。


👆希望我这个“异教徒”的“传教”能让你对edge稍微有点改观吧🤣

**Comment by apades** [comment]
> 实测chrome的0.5无论在chrome还是edge上依然有双重弹幕问题。

你这个能提供链接不，我还是找不着这种情况，我怀疑是启动2个监听器了，或者你把其他插件关了试试？

> 从116开始到现在126才把容易崩溃卡顿和红色tab栏给修了，我印象挺差的。

这我去年11月时116版本就提了，在chrome还是112时需要chrome://flags开启的就已经是非常流畅的，默认tab栏也是黑的，就edge在116时非常卡😓这感觉跟chromium没关系的就是他们套的docPIP外壳出问题了一直没修

> 我这边测试鲜艳模式是支持的，截图里的就是开了SVR的效果，**不然画面就是占满的。**

而且你这个什么意思啊，他video就这么小啊😧我记得我video都width + height: 100% important了

**Comment by Mishasama** [comment]
> 你这个能提供链接不，我还是找不着这种情况，我怀疑是启动2个监听器了，或者你把其他插件关了试试？

找到[冲突扩展](https://chromewebstore.google.com/detail/gfbfblhgcnaceejlekkogpbjjogdealk)了
棒子写的，没法交流🙃
~~要是你能把他的脚本的导出来用在TM里的话……~~
 
> 这我去年11月时116版本就提了，在chrome还是112时需要chrome://flags开启的就已经是非常流畅的，默认tab栏也是黑的，就edge在116时非常卡😓这感觉跟chromium没关系的就是他们套的docPIP外壳出问题了一直没修

谷歌是这样的……自己先用性能优化最好的版本，给大家开源另一套低性能的二手代码。这样就没人能轻易套壳撼动Chrome的地位了。
 
> 而且你这个什么意思啊，他video就这么小啊😧我记得我video都width + height: 100% important了

### SVR OFF
![image](https://github.com/user-attachments/assets/659e413b-1943-4af6-9b05-3de22a7d08aa)
### SVR ON
![image](https://github.com/user-attachments/assets/4a317cfe-bdc8-44ff-aba1-78b62ebc246c)
**截图中的视频流为160p**
正常情况下docPIP也是缩放到整个窗口的，但edge开了SVR后缩放就会失效，变成以实际分辨率来渲染，不带缩放的。
我这边没有RTX只能测试鲜艳模式（软件滤镜），也许你有RTX开的驱动模式或者超分模式（硬件加速）不会有问题。

**Comment by apades** [comment]
![image](https://github.com/user-attachments/assets/9d25da4b-b596-45aa-bd6b-0abd3af53318)

你发的这个插件不是他造成的吧，我看了他代码就这段是核心，里面没有修改什么东西或者dom啊

**Comment by Mishasama** [comment]
> 你发的这个插件不是他造成的吧

有劳你测试一下？我关掉它后就正常了。

**Comment by apades** [comment]
我装上测试了，没问题的

**Comment by apades** [comment]
https://www.awesomescreenshot.com/video/29643929?key=04c50caeaaf070814457a09d1c318d14

**Comment by apades** [comment]
> 我不懂……也许你可以给他优化一下整个USERJS？

他这个属于要改设计了，还不如重新写个但我懒了，我刚把他卸载了我画中画都流畅了🤣

**Comment by Mishasama** [comment]
> 我装上测试了，没问题的

你要先等页面加载完，不要点击PIP，再等个10秒左右。
然后点击PIP扩展的按钮，会发现第一次不会出现“要点击画面”的提示，而是一闪而过。
第二次点按钮才会出现提示，然后再顺利激活。

如果我也尽快激活PIP不出现两次问题的话也是不会出现弹幕重复的。
我猜就是这个“两次”捕获video导致的重复问题。

> > 我不懂……也许你可以给他优化一下整个USERJS？
> 
> 他这个属于要改设计了，还不如重新写个但我懒了，我刚把他卸载了我画中画都流畅了🤣

要不你看看能不能给我[这个](https://greasyfork.org/ja/scripts/491524-twitch-latency-overlay)小改一下就能显示左上角的那两个时间？
这个的性能也许会好一些？

---

另外，貌似只能显示文字弹幕，弹幕中的表情图都是没法显示出来的。

**Comment by apades** [comment]
> 你要先等页面加载完，不要点击PIP，再等个10秒左右。

好了终于找到问题了，确实是这个插件的问题，他onload后触发了click事件引发了我的user activation检测成功了😓我那原本是要打开画中画的但是失败了，又点了一次icon导致第二次初始化了

> 截图中的视频流为160p
正常情况下docPIP也是缩放到整个窗口的，但edge开了SVR后缩放就会失效，变成以实际分辨率来渲染，不带缩放的。
我这边没有RTX只能测试鲜艳模式（软件滤镜），也许你有RTX开的驱动模式或者超分模式（硬件加速）不会有问题

![image](https://github.com/user-attachments/assets/332013ac-cf47-441b-a389-b84b254af6e6)

感觉没法还原你这种强制渲染大小的情况啊，还是说3070默认开了

> 另外，貌似只能显示文字弹幕，弹幕中的表情图都是没法显示出来的。

这是我issue里提了，现在的弹幕是用canvas画的，光是画文字量多 + 高帧都跟不上的，图片就更不想了。现在再换html弹幕，跟重构代码绑一起了要晚点了

> 要不你看看能不能给我[这个](https://greasyfork.org/ja/scripts/491524-twitch-latency-overlay)小改一下就能显示左上角的那两个时间？

你这个脚本是私人的，没法看到的

**Comment by Mishasama** [comment]
> 还是说3070默认开了

![image](https://github.com/user-attachments/assets/f2fa2ef5-a50c-4dab-94f5-793de5587f6d)

你点进去可以看到不同的设置，试试里面的几个选项看看。
你可以用低分辨率来开关测试，看看画面有没有肉眼可见的变化就知道有没有默认开了。

> 跟重构代码绑一起了要晚点了

无所谓，不急。

> 你这个脚本是私人的，没法看到的

你用GitHub登入一下就好……只是限制了未登入来反扒。
实在不想登入的话就[看这](https://github.com/Mishasama/UserScript/blob/master/Misha's%20US/Twitch%20Latency%20Overlay.user.js)……~~顺手提个PR什么的~~
