### ISSUE TITLE
[Bug] 扩展浮层与 Twitch 播放器控件冲突

### ISSUE THREAD

**Issue by Mishasama** [apades/dmMiniPlayer#23]
# 1. 切片页面问题
在 Twitch [创建切片页面](https://clips.twitch.tv/create)时出现的问题。

![image](https://github.com/user-attachments/assets/327cc50d-8aaa-4b4e-b727-1809e4c194b4)

这个小东西居然会挡在整个播放器的上面，导致播放器的所有控件无法点击。

# 2. 直播/视频页面问题
同时这个东西也无法出现在其它页面的播放器上。

---
测试环境：
edge + chrome

扩展版本：
0.5

**Comment by apades** [comment]
直播那最近也发现了但是一直没管😗主要都用b站的，哈哈你常用twitch的话帮我找bug也挺好

**Comment by Mishasama** [comment]
> 哈哈你常用twitch的话帮我找bug也挺好

你要是乐意修那就太好了😄[^1]
[^1]: ~~就怕你回我“反正我不用，懒得修。想修你可以PR。”🤣~~

**Comment by apades** [comment]
你想提pr我更乐意哈，我就省事了😄0.5.2已经修了等审核了

**Comment by Mishasama** [comment]
> 你想提pr我更乐意哈，我就省事了😄

这么晚还在加班修复辛苦了。🙇🏻‍♀️
要是我能有提PR的本事的话我就不用怕得只能在issues里瑟瑟发抖了😂
