### ISSUE TITLE
与 Edge 浏览器的 SVR 兼容上的 BUG

### ISSUE THREAD

**Issue by Mishasama** [apades/dmMiniPlayer#26]
抽空录了个像
![75bc6756-6311-4f3b-8593-b4c2735fe735](https://github.com/user-attachments/assets/86e3c90d-6d1a-4c84-b9ea-71d2393036be)

## 测试环境
Microsoft Edge		127.0.2651.74
Chromium Version	127.0.6533.73
Windows 10 Version 21H2 (Build 19044.3086)

## SVR 模式
[艳丽模式](https://www.microsoft.com/zh-cn/edge/features/enhance-video?form=MA13FJ)（软件模拟）

**Comment by apades** [comment]
其实那个叫Video Super Resolution的不叫svr，而且他说的需要20以上显卡才支持你的显卡是不是这个的

![image](https://github.com/user-attachments/assets/5485f7b2-dedb-42ff-b4ab-fcaae421b56b)

vsr有3个模式，第一个完全没问题，就用第二个Vivid mode(生动模式)就会跟你截图的一样，这是浏览器设置我没法解决的

**Comment by Mishasama** [comment]
> 这是浏览器设置我没法解决的

你知道是为什么吗？
普通的PiP是不会有这个问题的。
（单纯好奇而已）

> svr

VSRSVR傻傻分不清啦~英文不及格的是这样的了😝
