### ISSUE TITLE
请求增加屏蔽部分弹幕类型的功能

### ISSUE THREAD

**Issue by sunxyw** [apades/dmMiniPlayer#3]
个人观看弹幕时喜欢关闭滚动弹幕，只开启顶部和底部弹幕，但在插件设置中未找到相关的屏蔽设定。

希望可以增加相关功能，感谢。

**Comment by sunxyw** [comment]
尝试了 bilibili evolved 方式后发现可以遵照 b 站的设定展示弹幕，但会有部分弹幕缺失。

**Comment by apades** [comment]
类型最近不会考虑，很多弹幕的bottom类型我都强制转了top，毕竟自己习惯只用滚动和top。

bilibili evolved的代码挺久了都没更新，之前用的时候发现经常弹幕不统一就基本放弃了，后续考虑更新下吧。
