### ISSUE TITLE
功能请求：允许扩展根据特定 URL 路径启用/禁用

### ISSUE THREAD

**Issue by yinkai666** [apades/dmMiniPlayer#31]
感谢您开发了这个非常有用的扩展！我有一个功能请求，希望能在特定的 URL 路径下启用或禁用扩展，而不仅仅是基于整个域名。例如，我希望扩展在 https://www.bilibili.com/ 和https://search.bilibili.com/上禁用，仅在 https://www.bilibili.com/video/ 上启用。

目前，Chrome 和 Edge 浏览器的扩展只能基于整个域名进行启用或禁用。能否增加一个选项，让用户根据更具体的 URL 路径来控制扩展的启用和禁用？

**Comment by apades** [comment]
那个浮动按钮挡住什么地方了嘛，我看看影响大不大。这个url过滤启动可以考虑下

**Comment by yinkai666** [comment]
没事了没事了，原来是我自己的弄错了，不是扩展的问题，谢谢
