### ISSUE TITLE
YouTube字幕功能無法正常運作

### ISSUE THREAD

**Issue by SnowAgar25** [apades/dmMiniPlayer#32]
## 環境

- Chrome 128.0.6613.115 字幕正常
- Vivaldi 6.9.3447.37 字幕正常
- Edge Beta 129.0.2792.12 字幕不正常
- Edge 128.0.2739.54 字幕不正常

Windows 10 Version 22H2 (OS Build 19045.4780)

## 問題

`dmMiniPlayer\src\web-provider\youtube\utils.ts` 

```javascript
return JSON.parse(
  '{' + htmlText.match(/ytInitialPlayerResponse = \{(.*)\};/)?.[1] + '}'
)
```

不知道為什麼 `/ytInitialPlayerResponse = \{(.*)\};/` 匹配到了多餘的 JS 代碼，導致 JSON 解析失敗。

## 錯誤

```
VM2775:1  Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 119273 (line 1 column 119274)
    at JSON.parse (<anonymous>)
    at getVideoInfo (utils.ts:12:15)
    at async getSubtitles2 (utils.ts:20:21)
    at async SubtitleManager.ts:10:28
```
![錯誤截圖2](https://github.com/user-attachments/assets/feddbd77-b59d-4d7c-addb-f057f5b719f2)

## 臨時解決方案

```javascript
/ytInitialPlayerResponse = \{(.*)\};var/
```

**Comment by apades** [comment]
这就奇怪了，我这边测试了好多都没问题的

**Comment by SnowAgar25** [comment]
剛剛試了一下把Cookie全部清除，結果字幕功能正常了
重新登入後也沒有發生這個錯誤，可能是Youtube的問題吧……

**Comment by SnowAgar25** [comment]
這個是錯誤時捕獲到的文本（`ytInitialPlayerResponse = \{(.*)\};`）
[result_test_bug.txt](https://github.com/user-attachments/files/16861874/result_test_bug.txt)

這個是清除Cookie恢復正常後捕獲到的文本
（截取到了和上面一樣的位置，不過match的結果是正確的）
[result_test_normal.txt](https://github.com/user-attachments/files/16861875/result_test_normal.txt)

**Comment by apades** [comment]
我看了2个文件这里`var ytInitialPlayerResponse = {};`都没东西啊🤔好奇怪啊还能有返回空的情况，这种情况`\{(.*)\};`的$1都会匹配错的

**Comment by SnowAgar25** [comment]
啊這，不是，我把裏面東西清空了，不然檔案太大，忘講了😅
