### ISSUE TITLE
看B站视频，经常会突然暴涨内存到吃满

### ISSUE THREAD

**Issue by u2shana** [apades/dmMiniPlayer#33]
16G内存，一口气突然从六七十用到90%多然后卡死的那种

频率还挺高的，触发条件不明确，有时是跳进度条触发、有时是连播到下一个视频触发（都在开启1.25倍速播放的情况下）

**Comment by u2shana** [comment]
> 16G内存，一口气突然从六七十用到90%多然后卡死的那种
> 
> 频率还挺高的，触发条件不明确，有时是跳进度条触发、有时是连播或者手动点下一个视频触发（都在开启1.25倍速播放的情况下）

**Comment by apades** [comment]
我去看了下内存，挺正常的波动也没有说会吃满。你看看是不是有些插件或者油猴脚本关了就好了，我有些代码注入了原有的api可能触发那些脚本的检测导致内存暴涨的
