### ISSUE TITLE
弹幕字体大小应跟随窗体尺寸而不是视频原始分辨率

### ISSUE THREAD

**Issue by Mishasama** [apades/dmMiniPlayer#34]
当从1080p等高分辨率向下变动（如360p）时就会出现如下情况：
👇👇👇
![image](https://github.com/user-attachments/assets/54e6e9af-4435-4359-b4a3-5006d4f20d6c)

（测试使用默认字体设置）
由于窗口尺寸没有改变，显示器分辨率也没有改变，这样的更改字体大小没有必要。

**Comment by Mishasama** [comment]
你不是写着有性能问题吗？我硬件比较老旧，而且开锐化，就没用HTML渲染。

**Comment by apades** [comment]
是可能存在的性能问题，我这边电脑双开1080视频gpu竟然处理不过来，我都怀疑只有我电脑锐化+html有问题，你要有时间可以测试下卡不卡呢

**Comment by Mishasama** [comment]
> 双开1080视频

双开？两个浏览器吗？

**Comment by apades** [comment]
同个浏览器2个tab双屏，不知道哪个window补丁版本我电脑就成这样了，这3070还不如960的80帧稳定

**Comment by Mishasama** [comment]
> 同个浏览器2个tab双屏

Chromium核心同一浏览器PiP不是只能存在一个？
如何两个tab实现两个PiP？

**Comment by apades** [comment]
我都说了嘛我电脑可能有问题的没测试过其他的，锐化那个我这边感受是挺好的，不开字体是模糊且白色有色差，毕竟我都一直用的chrome没有超分模式，而且锐化这个是用的css强制gpu渲染搞出来的，这个要是不好用还是可以关了的。我说的2tab就是2网页同时开视频，不是2pip，2pip只能通过chrome edge 2个实现

**Comment by Mishasama** [comment]
> 2网页同时开视频

这个在我这边似乎无法实现，因为后台分页貌似是不渲染视频画面的，只有音频在播放。
如果多窗口的话，那会因应是否采用硬解，与硬解自身的处理能力来决定性能。
在我的核显 `HD 530` 下通常能处理 `720p @ 60f @ ~4000kbps` × 5
而在独显 `GTX 1080` 下则能处理 `1080p @ 60f @ ~12000kbps` × 3
而不至于过载（看任务管理器的性能页）。

对于我来说，过载的通常是CPU而不是GPU……😂（很多网页元素、框架、JS等都只吃CPU）



> chrome没有超分模式

其实是有的，但正常来说是要用CLI参数启用的。不过你似乎已经用CSS强制启用了。



> 锐化这个是用的css强制gpu渲染搞出来的

如果是这样的话则完全依赖GPU的驱动设置了，效果会因人而异。性能影响也是。
## NV GPU 的情况

- 比如说RTX就会触发超分，这个依赖AI驱动的就非常吃配置，貌似只要一路1080p几乎就能吃满除4090外的所有显卡。
- 但非RTX的话则只会调用传统的视频锐化驱动，这个并不怎么吃性能，而且当初也是作为DLSS的下位替换而生的，所以对性能的影响非常小。

## 非 NV GPU 的情况
I和A都是调用GPU的视频锐化驱动进行处理的，由于也是专用模组，同时也是老技术，所以对性能的影响也是微乎其微。

---

按照目前的情报来分析，性能问题只会发生在启用了超分的RTX用户上。
那你要不要考虑针对你自己的情况来修复这个issue？
对我和其它没有`RTX ON`的人来说似乎不是一个容易被察觉到的问题。

**Comment by apades** [comment]
还有这种事，我就说怎么960比我3070还流畅的。就这个判断显卡要申请插件新权限，涉及新权限会触发更新警告的，还是算了吧不好解决。最近正要组一套770的集显机，我再试试效果怎样

**Comment by Mishasama** [comment]
> 看看怎么修

1. 检测串流地址变化（切换清晰度）
2. 重建 canvas

**Comment by apades** [comment]
好奇怪我现在试了下完全没有你说的那个字体模糊的情况，无论是我自己手动切分辨率还是auto限速让他720自动到360都没有。这个问题或许需要你那边提供更多信息或者你看怎么调试才行了

**Comment by Mishasama** [comment]
> 我现在试了下完全没有你说的那个字体模糊的情况

估计又是浏览器的bug……随着版本更新被修复了🤷🏻‍♀️

**Comment by apades** [comment]
那这个我只能加个设置看看了，不知道2canvas渲染会不会有性能损耗问题

**Comment by Mishasama** [comment]
> 那这个我只能加个设置看看了，不知道2canvas渲染会不会有性能损耗问题

为什么需要2canvas？是弹幕的渲染尺寸不能锁定吗？

**Comment by apades** [comment]
我被绕晕了，弹幕canvas本来就是跟着窗体大小来的，双视频模式才会被分辨率影响😓我刚看了下代码，可能还真跟你说的切换video源导致的，我看了代码可能是有这么个情况触发模糊，你下次再出现模糊情况可以试试调整窗口大小，看还糊不糊，还是糊那真没办法解决了

**Comment by Mishasama** [comment]
> 你下次再出现模糊情况可以试试调整窗口大小，看还糊不糊

👌
我一般是用默认大小不去动的，不知道为什么最近很少触发模糊了，以前的话会遇得比较频繁
