### ISSUE TITLE
与多重播放器（动态分辨率）设计不兼容

### ISSUE THREAD

**Issue by Mishasama** [apades/dmMiniPlayer#35]
![image](https://github.com/user-attachments/assets/5af1ef9e-46d4-483e-a1d4-9a745e0f1755)
当使用`自动`分辨率模式时，由于该技术采用同时使用多个播放器同时加载不同质量的音画流，导致扩展识别到多个播放器。扩展的按钮模块在点击画中画按钮后并不会随着PIP的弹出而消失，再次点击该按钮则会改为使用在后台暗中加载未播放的串流的播放器。这样反复点击按钮就会导致浏览器分页卡死。

**Comment by apades** [comment]
这个我不知道怎么搞的，我主账户带有一堆插件的就不会这样，只有这个插件的就会触发，可能你需要开这个模式比较好吧

![image](https://github.com/user-attachments/assets/abd1cc0e-6b46-4bfb-9c57-b3280bd2eae2)

**Comment by Mishasama** [comment]
你主账户检查是否有阻止自动降低分辨率之类的插件/脚本，或者设置了固定的分辨率。这个问题B站之类的采用相同技术的网站都会有。传统的PiP是不会有这问题的。
双视频虽然不影响原有的功能，但会造成额外的资源开销，并且在切换播放器的时候不会跟着切换。

理论上这个问题需要你主动检测（轮询）活跃播放器实时更新转移目标。

**Comment by apades** [comment]
双视频模式应该有些问题，总体是有检测播放器替换的，之前重构的播放器没怎么兼容转移模式之外的，最近修一下吧。双视频是用的canvas画每一帧的视频的，开销是没办法的，但这个体验是比下面2个还好的，能看60帧视频。如果没60帧需求也能用第三个

**Comment by Mishasama** [comment]
> 有检测播放器替换的

能检测多少个？
据我目测，自动清晰度的模式下会同时初始化所有的清晰度，也就是说有可能是同时存在着很多个播放器。但似乎并不是一直都全部同时加载，大多数都只是加载第一个ts进行测速，然后播放缓存最多的那个。
如果有更高清晰度的串流也达到了缓冲阈值的话就切换到那个清晰度。
反之，当前的清晰度缓冲下降到一定的阈值就会切换到更低的清晰度（如有）。
这么看来通常都会处于1~2个清晰度在后台同时缓冲着。

**Comment by apades** [comment]
就只有1个，通常来说这种都是会替换原有的video标签实现换源的，我就是监听这个video的父组件有没有新添加video为准[（具体逻辑）](https://github.com/apades/dmMiniPlayer/blob/main/src/utils/observeVideoEl.ts)。如果父组件里面有多个video的话，会导致选择不到正确的video，但一般后台加载的video不会放在父组件里的吧

**Comment by Mishasama** [comment]
> 但一般后台加载的video不会放在父组件里的吧

那这个我就不知道了。我只知道 Twitch 在切换清晰度的同时有一定概率会换服务器，类似 B 站的切换线路，有可能会销毁原来的 video 组件创建新的来替换。（也有可能本来就存在多套组件用于切换，所以触发了此 BUG）

**Comment by apades** [comment]
B站的是销毁旧的然后切换新的，这我重点测试的。你说的两套应该是直播和视频的吧，他2个切换源是不一样的操作的，直播是销毁和切换，视频是切换src

**Comment by Mishasama** [comment]
我们一直说的都是直播吧？

万一他连父组件一起销毁呢？甚至说整个框架？

**Comment by apades** [comment]
这不用担心的，我一路监听父组件到body的，其中一个没了就重新选取video。如果你说直播还有另一套做法的话，那我确实没见过

**Comment by Mishasama** [comment]
> 如果父组件里面有多个video的话，会导致选择不到正确的video

我回想了一下，好像开启了docPiP就会导致无法换线路，但换清晰度是可以的。
无法切换估计是因为video被转移了，原页面无法检测到video的状态，不知道是否要切换。

按照你描述的特性，估计是有至少两个video同时存在着的？

**Comment by apades** [comment]
https://www.awesomescreenshot.com/video/32163258?key=0e269976a28bfa295154a136d9f7c599

测了很多次还是没有发现多个video的情况，这里面还带着模糊问题的，实在找不到什么解决的方案了

**Comment by Mishasama** [comment]
你首先要看有没有载入多个不同的线路，比如lax、ams、lhr等，不能急着开docPiP，得先让它触发多开。如果一直都只有同组服务器，那估计是没有的。

话说你不是已经测出[复现方式](https://github.com/apades/dmMiniPlayer/issues/35#issuecomment-2362955215)了吗……？

**Comment by apades** [comment]
这个还只是偶发性的，现在又没了，实在没法找到解决方案了
