### ISSUE TITLE
添加本地字幕的文件选择器不能移动位置

### ISSUE THREAD

**Issue by M1s4k1** [apades/dmMiniPlayer#39]
在mac下(win未测试)
播放油管视频,启动画中画小窗后,点击添加新的字幕. 弹出finder选择本地文件.
这个finder窗口不能移动位置. 画中画小窗摸鱼基本都放在右下角,弹出的finder窗口也固定在右下角的位置, 不太方便

**Comment by apades** [comment]
这种调用系统的我没法操作，只能说这个api还是兼容性不太行
