### ISSUE TITLE
可不可以增加在视频外挂本地弹幕的功能

### ISSUE THREAD

**Issue by dusanjin94** [apades/dmMiniPlayer#42]
由于b站的动漫和谐太多，更有一些经典老番被下架处理，想要和过去一样愉快就着弹幕看番已经不太可能，目前的解决办法只有将动漫下载本地后再导入从弹幕网站下载的弹幕文件，十分麻烦
希望作者可以增加一个在网页视频挂载本地弹幕的功能
这样就可以在其他动漫网站看有弹幕的动漫了

**Comment by apades** [comment]
可以考虑加个，之前就想弄的但是比较懒

**Comment by apades** [comment]
已经加上了
