### ISSUE TITLE
无法区分油管直播和直播回放档

### ISSUE THREAD

**Issue by deerload** [apades/dmMiniPlayer#43]
首先感谢作者的辛劳，很小巧方便的插件，特别是网页能外挂ass字幕的功能，非常方便
但是在使用的时候发现油管的直播和直播回放没有区分，导致直播回放没办法使用外挂字幕
不知道这个细微的不足之处有没有改进的空间

**Comment by Xmarmalade** [comment]
disable `useIframeDetectionOnYT` option in settings
![image](https://github.com/user-attachments/assets/4d82afbe-4e97-4f0a-9813-09d2c5d29411)

**Comment by deerload** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by deerload** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
