### ISSUE TITLE
Twitch 直播时间不同步

### ISSUE THREAD

**Issue by Mishasama** [apades/dmMiniPlayer#44]
![image](https://github.com/user-attachments/assets/b5aa695a-3cc0-4360-a057-5737a545a2a7)
如图
偶然发现的，貌似只从打开页面的时间开始算？

**Comment by apades** [comment]
这是正常的，时间是用视频标签的时间来的，这样省事。好像目前就斗鱼时间是准的

**Comment by Mishasama** [comment]
那看来就斗鱼技术最落后了🤷🏻‍♀️搞适配就太麻烦了，就这样吧。
