### ISSUE TITLE
增加默认倍速1.25 1.5等

### ISSUE THREAD

**Issue by Mlk1225** [apades/dmMiniPlayer#46]
- 问题描述：目前在小窗状态下可供选择的默认倍速有0.5，1.0，2.0和3.0，但个人感觉很少用到3.0 ![image](https://github.com/user-attachments/assets/cc02415f-6027-48cd-b082-c76bda5ef048)

- 可能的解决办法：
    - 也许把3.0改成1.25或者1.5
    - 读取视频原页面提供的倍速选项作为小窗状态的倍速选项

**Comment by apades** [comment]
我没法知道视频播放器默认提供多少倍速选项，倒是挺多人提的默认倍速要改下确实可以考虑下
