### ISSUE TITLE
能否添加域名黑名单功能？

### ISSUE THREAD

**Issue by u2shana** [apades/dmMiniPlayer#47]
因为发现会和一些其他的脚本造成冲突导致播放异常，特意兼容也比较麻烦，感觉直接自定义ban域名了更方便

**Comment by u2shana** [comment]
今天发现，开启了黑名单之后，虽然在黑名单站点下插件确实不工作了，但是还是和其他脚本存在一些奇怪的兼容性问题。把本插件禁用后就没问题了

**Comment by apades** [comment]
一起会出问题的脚本能给我么，我看看是什么情况

**Comment by u2shana** [comment]
> 一起会出问题的脚本能给我么，我看看是什么情况

https://greasyfork.org/zh-CN/scripts/474507-wider-bilibili
一直都是这个脚本有兼容问题，经常出现打开页面播放器二次加载的问题，此时弹幕输出框还会被吞掉。
然后加入了黑名单后，现在二次加载问题没了，但是如果疯狂连按右方向键快进会卡住，此时有个明显特征就是清晰度、选集选项点不开了

**Comment by apades** [comment]
你现在插件是什么版本的呢，我刚试了下都挺正常的，也没有卡住、选项打不开问题

**Comment by u2shana** [comment]
> 你现在插件是什么版本的呢，我刚试了下都挺正常的，也没有卡住、选项打不开问题

试了下，最新的24版本好像顺带解决这个问题了。然后下了个23的dev版，问题秒复现

**Comment by apades** [comment]
哦哦那可能是这个[addEventListener注入](https://github.com/apades/dmMiniPlayer/compare/v0.6.23...v0.6.24#diff-8193951a721c00a65dabfb7ef6b952d15fb86971919e16ea729e5b6c662f5f3f)修了才好的，这个bug存在还挺久了上周才有人提🤣
