### ISSUE TITLE
对于特定类型的网页直播，画中画视频画面会卡住

### ISSUE THREAD

**Issue by yanruodi1412** [apades/dmMiniPlayer#50]
**Describe/描述**
对于斗鱼直播，如果直播页面并非常规直播间，则有可能会触发画中画卡死。

举例说明，图一为一般主播直播间：
![屏幕截图_22-11-2024_172536_www douyu com](https://github.com/user-attachments/assets/163d6003-949b-4ab4-8c3f-78a884d75543)

图二中，由于为特定活动，因此除直播画面外，还有活动宣传、赛程介绍、切换直播间等按钮：
![屏幕截图_22-11-2024_172513_www douyu com](https://github.com/user-attachments/assets/c88bdb9a-9e20-4eeb-ad7f-e5c8dd209680)

对于图二这类直播间，画中画视频有极大概率卡死。对于常规直播间，一般不易卡死。

**Browser/浏览器**
 - OS: windows 11
 - Browser: Microsoft Edge
 - Version 131.0.2903.51 (正式版本) (64 位)

**Comment by apades** [comment]
我之前就不理解斗鱼的这种活动页内存占用怎么这么高，我的8g旧机子光是开一个都卡😅这个我可没办法搞，我去试了下这个cs2的活动页也没问题

**Comment by yanruodi1412** [comment]
updates：
在0.6.17 or 0.6.18版本后问题已解决，可能是0.6.18的修复起作用了，感谢作者

**Comment by apades** [comment]
emmm我也没改什么啊🤣
