### ISSUE TITLE
entry-world.js的import对使用了importmap的网站有破坏性效果

### ISSUE THREAD

**Issue by shc0743** [apades/dmMiniPlayer#51]
**Describe/描述**
如果网站使用了 importmap ，由于`⚡ run world script`在页面载入前就已运行，importmap就无法生效，产生`An import map is added after module script load was triggered.`
从而在网站脚本正式运行时产生：`Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".` 类似问题
导致网站被破坏无法正常载入
![Snipaste_2024-12-01_09-42-25](https://github.com/user-attachments/assets/90c1b14e-eb6d-4f59-8d28-8b8dc66c8837)
MDN Reference: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/script/type/importmap

# 怎么触发，有截图更好
示例页面：https://shc7432.github.io/public/demo/event-20241201-pipbug/  (源码：https://github.com/shc7432/public/tree/master/demo/event-20241201-pipbug )

## Steps to reproduce
1. Access the example page above with extension enabled -> Site was broken with error message `Uncaught TypeError: Failed to resolve module specifier "my". Relative references must start with either "/", "./", or "../".`
2. Disable the extension and reload the page -> Site works normally

**Browser/浏览器**
 - OS:
   - [x] Windows
   - [ ] Mac
   - [ ] Ubuntu
   - [ ] Ohter, input your OS ______
 - Browser
   - [x] Chrome
   - [ ] Edge
   - [ ] Ohter, input your browser ______
 - Version [e.g. 131.0.6778.86] 131.0.6778.86

**Environment/环境**
 - [ ] 是否关闭其他插件/Have you close other extensions?
 - [x] 是否禁用自定义js/Have you disable custom js file?

**Comment by apades** [comment]
设置里有禁用网站功能，可以先加个127.0.0.1，我过段时间看看怎么个回事

**Comment by shc0743** [comment]
> 设置里有禁用网站功能，可以先加个127.0.0.1，我过段时间看看怎么个回事

我是直接在Chrome设置里面把扩展程序访问权限设为只有bilibili.com解决了（因为只在bilibili上使用）
具体问题应该就是content script执行时机不合适，在页面importmap完成加载前就注入了，可以调整一下执行时机（其他扩展都没有这个问题）

**Comment by apades** [comment]
> 我是直接在Chrome设置里面把扩展程序访问权限设为只有bilibili.com解决了（因为只在bilibili上使用） 具体问题应该就是content script执行时机不合适，在页面importmap完成加载前就注入了，然而规范中规定importmap加载前不能加载**module script**否则无效（普通script可以），可以调整一下执行时机或者修改content script类型（改为非module）（其他扩展都没有这个问题）
> 
> importmap作用是在浏览器端让指定module可以直接按名称加载而不需要写完整路径，比如，没有importmap，浏览器端原生加载vue需要 `import {createApp} from './resources/lib/vue/vue.esm_browser.prod.js'` 如果使用importmap指定好这个路径，就可以直接 `import {createApp} from 'vue'` 但由于是比较新的特性所以在生产环境中使用较少（具体可以参考[测试页面](https://shc7432.github.io/public/demo/event-20241201-pipbug/) 或者 [本人的相关项目](https://github.com/shc0743/MyPN532/blob/main/web/index.html) (问题起初就是在这里发现的)）

entry-world.js是运行在top层的不是cs层，这个js一开始就是为了注入和劫持网页原生API诞生的，只能越快执行越好，cs层的js不会跟你主线程js抢import的🤣importmap这玩意还是挺少网站用的，不过后续注入js我应该会改成单文件不搞分包import了
