### ISSUE TITLE
b站的侧边栏分集消失了

### ISSUE THREAD

**Issue by qstdnx** [apades/dmMiniPlayer#54]
1进入小窗后能否自动调整小窗比例符合视频比例，每次进入小窗都有黑边需要手动调整。
2小窗好像不支持b站的分集，只有推荐，能否支持在分集内跳转。

**Comment by apades** [comment]
1. https://github.com/apades/dmMiniPlayer/wiki/FAQ%E2%80%90zh#%E7%94%BB%E4%B8%AD%E7%94%BB%E6%89%93%E5%BC%80%E7%9A%84%E8%A7%86%E9%A2%91%E6%9C%89%E9%BB%91%E8%BE%B9
2. 应该是啊b改了网页，原本是支持分集的，近期会修复
