### ISSUE TITLE
播放器替换不兼容直播？

### ISSUE THREAD

**Issue by Mishasama** [apades/dmMiniPlayer#59]
**Describe/描述**
Twitch直播

**Browser/浏览器**
 - OS:
   - [x] Windows
   - [ ] Mac
   - [ ] Ubuntu
   - [ ] Ohter, input your OS ______
 - Browser
   - [ ] Chrome
   - [x] Edge
   - [ ] Ohter, input your browser ______
 - Version [131.0.2903.86]

**Environment/环境**
 - [x] 是否关闭其他插件/Have you close other extensions?
 - [x] 是否禁用自定义js/Have you disable custom js file?

**Comment by apades** [comment]
你先把其他插件关了试试，我是测试过twitch没问题的

**Comment by Mishasama** [comment]
https://github.com/user-attachments/assets/498ff09b-6d5f-443d-bd4a-d7829bc561b3

无Twitch相关插件时👆
