### ISSUE TITLE
切换标签自动小窗后点击返回原视频会自动暂停

### ISSUE THREAD

**Issue by ydivho12123** [apades/dmMiniPlayer#61]
直播从小窗切换回原窗口不会暂停，但视频会自动暂停，不知道是不是bug还是特性，如果是特性很希望可以添加一个不自动暂停的功能按钮

**Comment by apades** [comment]
不想要这个功能就关了这个
![image](https://github.com/user-attachments/assets/db134efa-4e29-426c-aed8-061fed1bfed9)
