### ISSUE TITLE
看斗鱼直播用PIP播几分钟后画面会卡住

### ISSUE THREAD

**Issue by G0blinS1ayer** [apades/dmMiniPlayer#62]
如题，看斗鱼直播用PIP播几分钟后画面会卡住，但是声音和弹幕继续正常播放和滚动，虽然用了很久但不知道建议用哪种播放模式……？（浏览器是chrome 版本 131.0.6778.140（正式版本） （64 位））

**Comment by apades** [comment]
才发现斗鱼的代码写反了哈哈，明天发布个修复的
