### ISSUE TITLE
项目开源协议问题

### ISSUE THREAD

**Issue by yingziwu** [apades/dmMiniPlayer#63]
注意到当前项目部分代码基于 [wbt5/real-url](https://github.com/wbt5/real-url)  项目衍生而来，而 wbt5/real-url 项目开源协议是 [GPL 2.0](https://github.com/wbt5/real-url/blob/master/LICENSE)，而当前项目的 license 为 [CC BY-NC 4.0](https://github.com/apades/dmMiniPlayer/blob/0ad4c6074e82148f1394867b5eb466f1b2f7e8f8/LICENSE)。
CC BY-NC 协议并不兼容 GPL 2.0 协议，为了避免可能的版权问题，建议作者将当前项目的开源协议修改为与兼容 GPL 2.0 的开源协议或者直接移除基于wbt5/real-url 项目的衍生代码。

**Comment by apades** [comment]
看了下确实是有点问题，谢谢提醒。GPL那段代码现在用不着，也该删掉了
